### ISSUE TITLE
Invalid latest nord.xml

### ISSUE THREAD

**Issue by PyvesB** [arcticicestudio/nord-eclipse-syntax#9]
Hello there,

When trying to import the latest nord.xml, the following error message appears:
![Screenshot 2019-09-04 at 15 42 27](https://user-images.githubusercontent.com/10694593/64265333-a37d8880-cf2a-11e9-8a84-ea29c7dc96f1.png)

Looking at the contents of the file, the copyright header appears before the XML declaration, which I believe is invalid.

Cheers,

Pyves

**Comment by arcticicestudio** [comment]
Hi @PyvesB :wave:, thanks for your contribution :+1:
Sorry for the delay, unfortunately my free time to work on Nord is limited.

Thanks for the PR, I'll merge it for the next release version [0.2.0][].

[0.2.0]: https://github.com/arcticicestudio/nord-eclipse-syntax/projects/3

**Comment by PyvesB** [comment]
Thanks @arcticicestudio! I noticed that some images were broken in the README, I opened https://github.com/arcticicestudio/nord-eclipse-syntax/pull/11 to take care of that. 👍
